// Animation names
#define AMMOHANDLER_ANIM_DEFAULT 0

// Color names

// Patch names

// Names of collision boxes
#define AMMOHANDLER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define AMMOHANDLER_ATTACHMENT_357 0
#define AMMOHANDLER_ATTACHMENT_AR2 1
#define AMMOHANDLER_ATTACHMENT_COMBINEBALL 2
#define AMMOHANDLER_ATTACHMENT_BOLTS 3
#define AMMOHANDLER_ATTACHMENT_PISTOL 4
#define AMMOHANDLER_ATTACHMENT_SMG1 5
#define AMMOHANDLER_ATTACHMENT_SMG1GRENADE 6
#define AMMOHANDLER_ATTACHMENT_SPAS 7
#define AMMOHANDLER_ATTACHMENT_GRENADE 8
#define AMMOHANDLER_ATTACHMENT_ROCKET 9
#define AMMOHANDLER_ATTACHMENT_CRATE 10

// Sound names
