// Animation names
#define GRAVITYGUN_ANIM_DRAW 0
#define GRAVITYGUN_ANIM_FIRE 1
#define GRAVITYGUN_ANIM_FIREOPEN 2
#define GRAVITYGUN_ANIM_HOLD 3
#define GRAVITYGUN_ANIM_HOLSTER 4
#define GRAVITYGUN_ANIM_IDLE 5
#define GRAVITYGUN_ANIM_IDLEOPEN 6
#define GRAVITYGUN_ANIM_PRONGSOPEN 7
#define GRAVITYGUN_ANIM_PRONGSCLOSE 8

// Color names

// Patch names

// Names of collision boxes
#define GRAVITYGUN_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define GRAVITYGUN_ATTACHMENT_HAND 0
#define GRAVITYGUN_ATTACHMENT_FLARE 1
#define GRAVITYGUN_ATTACHMENT_CORE1 2
#define GRAVITYGUN_ATTACHMENT_CORE2 3
#define GRAVITYGUN_ATTACHMENT_CHARGE1 4
#define GRAVITYGUN_ATTACHMENT_CHARGE2 5
#define GRAVITYGUN_ATTACHMENT_LAUNCH 6
#define GRAVITYGUN_ATTACHMENT_COREGLOW1 7
#define GRAVITYGUN_ATTACHMENT_COREGLOW2 8
#define GRAVITYGUN_ATTACHMENT_BASEGLOW 9

// Sound names
