// Animation names
#define ITEMHANDLER_ANIM_DEFAULT 0

// Color names

// Patch names

// Names of collision boxes
#define ITEMHANDLER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ITEMHANDLER_ATTACHMENT_357 0
#define ITEMHANDLER_ATTACHMENT_AR2 1
#define ITEMHANDLER_ATTACHMENT_CROSSBOW 2
#define ITEMHANDLER_ATTACHMENT_GRENADE 3
#define ITEMHANDLER_ATTACHMENT_USP 4
#define ITEMHANDLER_ATTACHMENT_RPG 5
#define ITEMHANDLER_ATTACHMENT_SPAS 6
#define ITEMHANDLER_ATTACHMENT_SMG1 7
#define ITEMHANDLER_ATTACHMENT_CROWBAR 8
#define ITEMHANDLER_ATTACHMENT_G3SG1 9
#define ITEMHANDLER_ATTACHMENT_GRAVITYGUN 10

// Sound names
