// Animation names
#define WEAPONITEMHANDLER_ANIM_DEFAULT 0

// Color names

// Patch names

// Names of collision boxes
#define WEAPONITEMHANDLER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define WEAPONITEMHANDLER_ATTACHMENT_357 0
#define WEAPONITEMHANDLER_ATTACHMENT_AR2 1
#define WEAPONITEMHANDLER_ATTACHMENT_CROSSBOW 2
#define WEAPONITEMHANDLER_ATTACHMENT_GRENADE 3
#define WEAPONITEMHANDLER_ATTACHMENT_USP 4
#define WEAPONITEMHANDLER_ATTACHMENT_RPG 5
#define WEAPONITEMHANDLER_ATTACHMENT_SPAS 6
#define WEAPONITEMHANDLER_ATTACHMENT_SMG1 7
#define WEAPONITEMHANDLER_ATTACHMENT_CROWBAR 8
#define WEAPONITEMHANDLER_ATTACHMENT_G3SG1 9
#define WEAPONITEMHANDLER_ATTACHMENT_GRAVITYGUN 10

// Sound names
